apiVersion: v1
kind: Pod
metadata:
  name: test-pod1
  labels:
    app: k8s-test
    env: development
    version: v1.0.1
spec:
  containers:
    - name: k8s-test
      image: ahmedgodaa/k8s-test:v1.0.1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080