apiVersion: v1
kind: Service
metadata:
  name: k8s-test
  namespace: staging
spec:
  selector:
    app: k8s-test
    env: staging
    version: v1.0.1
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort
