apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-test
  namespace: development
  labels:
    app: k8s-test
    env: development
    version: v1.0.1
spec:
  selector:
    matchLabels:
      app: k8s-test
      env: development
      version: v1.0.1
  replicas: 2
  template:
    spec:
      containers:
        - name: k8s-test
          image: ahmedgodaa/k8s-test:v1.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

