apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-test
  namespace: development
  labels:
    app: k8s-test
    env: development
    version: v1.0.1
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 30%
  selector:
    matchLabels:
      app: k8s-test
      env: development
      version: v1.0.1
  replicas: 10
  template:
    metadata:
      labels:
        app: k8s-test
        env: development
        version: v1.0.1
    spec:
      containers:
        - name: k8s-test
          image: ahmedgodaa/k8s-test:v1.0.1-dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

