apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.release.namespace }}
spec:
  selector:
    app: {{ .Values.service.name }}
    env: {{ .Values.release.namespace }}
    version: {{ .Values.image.tag }}
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort