apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.environment }}
spec:
  selector:
    app: {{ .Values.service.name }}
    env: {{ .Values.environment }}
    version: {{ lower .Values.image.tag }}{{ if eq .Values.environment "development"}}-dev{{else if eq .Values.environment "staging" }}-stg{{end}}
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort