name: Build and push Docker images

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Determine current version
        id: version
        run: echo "::set-output name=version::$(git describe --tags)"

      - name: Build and Push Cart Service Docker image
        run: |
          cd k8s-test
          chmod +x gradlew
          ./gradlew build
          docker build -t ahmedgodaa/k8s-test:${{ steps.version.outputs.version }} .
          docker push ahmedgodaa/k8s-test:${{ steps.version.outputs.version }}
