name: Build and push Docker images

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull latest Docker image 
        run: docker pull ahmedgodaa/k8s-test:latest

      - name: Extract current version
        id: extract_current_version
        run: echo "::set-output name=version::$(docker images ahmedgodaa/k8s-test:latest --format '{{.Tag}}')"

      - name: Bump version 
        id: bump_version
        run: |
          version=${{ steps.extract_current_version.outputs.version }}
          parts=( ${version//./ } )
          parts[2]=$((parts[2]+1))
          echo "::set-output name=new_version::${parts[0]}.${parts[1]}.${parts[2]}}"

      - name: Set up JDK 17

      - name: Login to Docker Hub

      - name: Build and Push Docker image
        run: |
          docker build -t ahmedgodaa/k8s-test:${{ steps.bump_version.outputs.new_version }} .  
          docker push ahmedgodaa/k8s-test:${{ steps.bump_version.outputs.new_version }}
